import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
 
// metadata is used to set the title and description of the page
// this is used to make the page more SEO friendly
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* anything here appears on every page */}
        <Link href="/"> Home | </Link>
        <Link href="/about">About | </Link>
        <Link href="/contact">Contact | </Link>
        <Link href="/users">Users</Link>
        {children} {/* this is where the page content goes */}
      </body>
    </html>
  );
}
